---
name: libTranslator
main: blugin\lib\libTranslator
version: 1.0.0
api: [3.0.0, 4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: "[lib] Language management library for automatic translation"
...